import Banner from "../models/AdminBannerModel.js";
import mongoose from "mongoose";

// ====================================================================
// --- 1. CREATE NEW BANNER (Admin Only) ------------------------------
// ====================================================================
export const createBanner = async (req, res) => {
  try {
    const { 
      title, 
      subtitle, 
      click_action_type, 
      target_destination, 
      sort_order, 
      start_date, 
      end_date, 
      target_city,
      is_active 
    } = req.body;

    // Validate that a file payload artifact was actually processed by middleware
    if (!req.file) {
      return res.status(400).json({ 
        success: false, 
        message: "A structural graphic layout banner image file asset is required." 
      });
    }

    // Capture the relative storage route path generated by upload engines
    const imagePath = `/uploads/${req.file.filename}`;

    const newBanner = await Banner.create({
      title,
      subtitle,
      image: imagePath,
      click_action_type,
      target_destination,
      sort_order: Number(sort_order) || 0,
      start_date: new Date(start_date),
      end_date: new Date(end_date),
      target_city: target_city ? target_city.toLowerCase().trim() : "all",
      is_active: is_active !== undefined ? is_active : true
    });

    return res.status(201).json({
      success: true,
      message: "Administrative campaign banner created successfully.",
      data: newBanner
    });

  } catch (error) {
    console.error("Create Banner Error:", error);
    return res.status(500).json({
      success: false,
      message: "An internal server error occurred while registering the banner."
    });
  }
};

// ====================================================================
// --- 2. GET ALL BANNERS (Admin Management List Grid view) -----------
// ====================================================================
export const getAllBannersAdmin = async (req, res) => {
  try {
    // Returns everything ordered by sort slot values then absolute registration chronology
    const banners = await Banner.find({}).sort({ sort_order: 1, createdAt: -1 });

    return res.status(200).json({
      success: true,
      count: banners.length,
      data: banners
    });
  } catch (error) {
    console.error("Get Admin Banners Error:", error);
    return res.status(500).json({
      success: false,
      message: "Failed to collect complete system banner matrices."
    });
  }
};

// ====================================================================
// --- 3. UPDATE BANNER (Admin Only) ----------------------------------
// ====================================================================
export const updateBanner = async (req, res) => {
  try {
    const { id } = req.params;

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return res.status(400).json({ success: false, message: "Invalid Banner ID format." });
    }

    const banner = await Banner.findById(id);
    if (!banner) {
      return res.status(404).json({ success: false, message: "Promotional banner target registry file not found." });
    }

    // Construct modification map fields directly from input payloads
    const fieldsToUpdate = { ...req.body };

    // If an alternate image payload exists, switch the tracking reference string
    if (req.file) {
      fieldsToUpdate.image = `/uploads/${req.file.filename}`;
    }

    if (fieldsToUpdate.target_city) {
      fieldsToUpdate.target_city = fieldsToUpdate.target_city.toLowerCase().trim();
    }

    const updatedBanner = await Banner.findByIdAndUpdate(
      id,
      { $set: fieldsToUpdate },
      { new: true, runValidators: true }
    );

    return res.status(200).json({
      success: true,
      message: "Administrative campaign properties updated successfully.",
      data: updatedBanner
    });

  } catch (error) {
    console.error("Update Banner Error:", error);
    return res.status(500).json({
      success: false,
      message: "An error occurred while modifying asset parameters."
    });
  }
};

// ====================================================================
// --- 4. PERMANENT DELETE BANNER (Admin Only) ------------------------
// ====================================================================
export const deleteBanner = async (req, res) => {
  try {
    const { id } = req.params;

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return res.status(400).json({ success: false, message: "Invalid ID parameter format." });
    }

    const deletedBanner = await Banner.findByIdAndDelete(id);
    if (!deletedBanner) {
      return res.status(404).json({ success: false, message: "Banner item context missing from database target records." });
    }

    // Optional: Add an file system module integration rule 'fs.unlink' here to erase the file from your local disk array

    return res.status(200).json({
      success: true,
      message: "Administrative campaign banner wiped permanently from layout directory slots."
    });
  } catch (error) {
    console.error("Delete Banner Error:", error);
    return res.status(500).json({
      success: false,
      message: "An error occurred during transaction execution processing paths."
    });
  }
};

// ====================================================================
// --- 5. GET LIVE CITY BANNERS (Client App Active Carousel Stream) ----
// ====================================================================
export const getActiveUserBanners = async (req, res) => {
  try {
    const { city } = req.query;
    const rightNow = new Date();

    // Baseline constraints: Must be active and run inside the present timestamp window
    const userFeedQuery = {
      is_active: true,
      start_date: { $lte: rightNow },
      end_date: { $gte: rightNow }
    };

    // If city is requested, pull matching city items or items designated as global "all" fallbacks
    if (city) {
      userFeedQuery.target_city = { $in: [city.trim().toLowerCase(), "all"] };
    }

    const liveBanners = await Banner.find(userFeedQuery)
      .sort({ sort_order: 1, createdAt: -1 })
      .lean();

    return res.status(200).json({
      success: true,
      totalLiveItems: liveBanners.length,
      data: liveBanners
    });

  } catch (error) {
    console.error("Get Active Feed User Banners Error:", error);
    return res.status(500).json({
      success: false,
      message: "Failed to assemble live carousel graphics stream."
    });
  }
};