import SubOfferType from "../models/subOfferTypeModel.js";
import OfferType from "../models/offer_type.js";
import mongoose from "mongoose";

// ==========================================
// 1. CREATE SUB-OFFER TYPE (With File Path)
// ==========================================
export const createSubOfferType = async (req, res) => {
  try {
    const { offertype_id, label, description } = req.body;

    if (!offertype_id || !label) {
      return res.status(400).json({ 
        success: false, 
        message: "Parent ID links and label elements are required parameters." 
      });
    }

    if (!mongoose.Types.ObjectId.isValid(offertype_id)) {
      return res.status(400).json({ success: false, message: "Invalid Parent Master ID format." });
    }

    const parentCategory = await OfferType.findById(offertype_id);
    if (!parentCategory) {
      return res.status(404).json({ success: false, message: "Parent target node mapping missing." });
    }

    const value = label.toLowerCase().trim().replace(/[^\w\s-]/g, "").replace(/[\s_-]+/g, "-");
    
    // Robust case-insensitive validation lookup
    const explicitDuplicate = await SubOfferType.findOne({ 
      offertype_id, 
      value: { $regex: `^${value}$`, $options: "i" } 
    });
    
    if (explicitDuplicate) {
      return res.status(400).json({ 
        success: false, 
        message: "This sub-category definition already exists under this parent profile." 
      });
    }

    // Process local server file storage paths generated by your Multer router layer
    let iconPath = "";
    if (req.file) {
      iconPath = `/uploads/${req.file.filename}`;
    }

    const newSubOffer = new SubOfferType({
      offertype_id,
      value,
      label,
      description,
      icon: iconPath // Storing file relative string path explicitly
    });

    await newSubOffer.save();
    res.status(201).json({ success: true, data: newSubOffer });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// ==========================================
// 2. READ ALL SUB-OFFERS BELONGING TO A PARENT
// ==========================================
export const getSubOffersByParent = async (req, res) => {
  try {
    const { id } = req.params;

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return res.status(400).json({ success: false, message: "Invalid Category parameter format configuration." });
    }

    const subTypes = await SubOfferType.find({ offertype_id: id }).sort({ label: 1 });
    res.status(200).json({ success: true, data: subTypes });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// ==========================================
// 3. UPDATE SUB-OFFER TYPE (With File Path Support)
// ==========================================
export const updateSubOfferType = async (req, res) => {
  try {
    const { id } = req.params;
    const { label, description, isActive } = req.body;

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return res.status(400).json({ success: false, message: "Invalid Sub-Offer targeted format payload ID." });
    }

    const subType = await SubOfferType.findById(id);
    if (!subType) {
      return res.status(404).json({ success: false, message: "Sub-offer target data profile missing." });
    }

    const parentCategory = await OfferType.findById(subType.offertype_id);
    
    if (!req.admin && parentCategory?.created_by_type === "admin") {
      return res.status(403).json({ 
        success: false, 
        message: "Unauthorized: Core system child configurations are locked." 
      });
    }

    if (label) {
      subType.label = label;
      subType.value = label.toLowerCase().trim().replace(/[^\w\s-]/g, "").replace(/[\s_-]+/g, "-");
    }
    if (description !== undefined) subType.description = description;
    if (isActive !== undefined) subType.isActive = isActive;
    
    // Check if a brand-new icon image binary path replaced the current file storage
    if (req.file) {
      subType.icon = `/uploads/${req.file.filename}`;
    }

    await subType.save();
    res.status(200).json({ success: true, data: subType });
  } catch (error) {
    console.log(error)
    res.status(500).json({ success: false, message: error.message });
  }
};

// ==========================================
// 4. DELETE INDIVIDUAL SUB-OFFER TYPE
// ==========================================
export const deleteSubOfferType = async (req, res) => {
  try {
    const { id } = req.params;

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return res.status(400).json({ success: false, message: "Malformed target structural parameters." });
    }

    const subType = await SubOfferType.findById(id);
    if (!subType) {
      return res.status(404).json({ success: false, message: "Target child data element does not exist." });
    }

    const parentCategory = await OfferType.findById(subType.offertype_id);
    if (!req.admin && parentCategory?.created_by_type === "admin") {
      return res.status(403).json({ 
        success: false, 
        message: "Core infrastructure categories cannot be broken down by standard tenants." 
      });
    }

    await SubOfferType.findByIdAndDelete(id);
    res.status(200).json({ success: true, message: "Sub-category entity deleted successfully from root tables." });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};